export const SET_PRODUCT = 'SET_PRODUCT'
export const PUSH_PRODUCT_TO_CART = 'PUSH_PRODUCT_TO_CART'
export const INCREMENT_ITEM_QUANTITY = 'INCREMENT_ITEM_QUANTITY'
export const DECREMENT_PRODUCT_INVENTORY = 'DECREMENT_PRODUCT_INVENTORY'
export const EMPTY_CART = 'EMPTY_CART'
export const SET_CHECKOUT_STATUS = 'SET_CHECKOUT_STATUS'


